name: permeation-env
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - python==3.12
  - matplotlib
  - numpy
  - pandas
  - pillow
  - scipy
  - openpyxl
  - conda-forge::darkdetect
  - bioconda::customtkinter
  - ruff